### ISSUE TITLE
Is the check on the 99 ApiTotalUsage enough ?

### ISSUE THREAD

**Issue by nvuillam** [pozil/legacy-api-scanner#5]
I don't know ApiTotalUsage behaviour, but I saw in the code that the checks are made on the latest 99 ApiTotalUsage

Do you think there are cases where LegacyApi could be found in more than 99 entries ?

If yes, I could update [sfdx-hardis command](https://hardisgroupcom.github.io/sfdx-hardis/hardis/org/diagnose/legacyapi/) using one of the following ways:
- Update dynamically the apex script to play with the counter and call it using 1,99, then 100, 199, etc... until there are no results
- Recode apex script in typescript to make the requests using jsforce queries

**Comment by pozil** [comment]
Hi @nvuillam, the reason why I limited my checks to 99 entries is that we only can do a maximum of 100 SOQL queries in an Apex transaction. `ApiTotalUsage` log files are quite large for production orgs so I can only retrieve them one by one in order to avoid heap size errors.
More details can be found in this [Twitter thread](https://twitter.com/emgforce__c/status/1426092799099817998).

I wanted an easy setup with no installation and I thought that I could parse the logs with Apex but it's probably not the right language for this kind of task. I agree that we'll likely need another version in JS or other to deal with production org data.

**Comment by nvuillam** [comment]
https://github.com/hardisgroupcom/sfdx-hardis/blob/alpha/src/commands/hardis/org/diagnose/legacyapi.ts#L132

Work in progress.
And it also generates a detailed CSV file with warning and errors

If someone has the format of EventLogFile typed ApiTotalUsage, it would help :) ( I didn't find an org with such records yet)

**Comment by pozil** [comment]
Here's the log file that I got when I wrote the post.
[ApiTotalUsage.csv](https://github.com/pozil/legacy-api-scanner/files/6986394/ApiTotalUsage.csv)

**Comment by nvuillam** [comment]
Thanks for the help, it allowed me to successfull test with hardcoded values :)

Now all is needed is a real-world very old org to confirm ^^

```shell
sfdx plugins:install sfdx-hardis
sfdx hardis:org:diagnose:legacyapi
```

Note: I also implemented [severity levels](https://github.com/hardisgroupcom/sfdx-hardis/blob/master/src/commands/hardis/org/diagnose/legacyapi.ts)
 
![image](https://user-images.githubusercontent.com/17500430/129489457-dff0668d-c621-4f27-9a31-ab1be1831d41.png)

**Comment by nvuillam** [comment]
![image](https://user-images.githubusercontent.com/17500430/130417165-a10b67ec-3d68-4f84-885a-a8c8c875f11f.png)

It seems it's working... but I can't succeed to have the detailed logs... @pozil maybe you have some on your test org ? 👼

**Comment by pozil** [comment]
@nvuillam sorry, I didn't say this earlier but I got the logs from one of the Salesforce APIs Product Managers. Unfortunately I don't have direct access to an org with legacy API calls in the logs.

**Comment by nvuillam** [comment]
@pozil > A [twitter trailblaizer](https://twitter.com/emgforce__c) has run the command on one of its old client org and it works :)

![image](https://user-images.githubusercontent.com/17500430/131793893-77d98a92-4d11-4657-9c9a-4eca936dc172.png)

Maybe we could benefit of your followers network to try to find other orgs ? 👼 

Instructions are simple :)

Install sfdx then ->

```shell
sfdx plugins:install sfdx-hardis
sfdx hardis:org:diagnose:legacyapi
```

**Comment by pozil** [comment]
@nvuillam sure, go ahead a tweet it. I will relay the message.

**Comment by nvuillam** [comment]
@pozil that's great, thanks a lot ! :)

https://twitter.com/NicolasVuillamy/status/1433376346663792651?s=20

I updated the command doc for easier handling

https://hardisgroupcom.github.io/sfdx-hardis/hardis/org/diagnose/legacyapi/

**Comment by nvuillam** [comment]
@pozil thanks for the [retweet](https://twitter.com/PhilippeOzil/status/1433418027677138944?s=20), it seems it reached some audience :)

Let's wait for feedbacks now ... I'd really like to have some real-life CSV logs of all deprecated API calls, that would allow us to provide guidelines about how to analyze it, and how to solve the issues ... to avoid to see production orgs exploding ^^

**Comment by nvuillam** [comment]
@pozil I wrote a blog article about sfdx-hardis command, and named you in the special thanks at the end, if for some reason you prefer not to be name, please let me know and i'll update the article :)

https://nicolasvuillamy.medium.com/handle-salesforce-api-versions-deprecation-like-a-pro-335065f52238

https://twitter.com/NicolasVuillamy/status/1441685264179601408?s=20

**Comment by pozil** [comment]
Nice, thanks for the heads up and congrats for the contribution.
I'm happy to have my name in there :)
